export const PROFILE_PICTURE = "PROFILE_PICTURE";
export const PRODUCT_IMAGE = "PRODUCT_IMAGE";
export const PRODUCT_VIDEO = "PRODUCT_VIDEO";
export const WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL";
